import type { SlimChallengeRecord } from "$lib";
import { readable, writable } from "svelte/store";

const allLocations: { id: string; name: string; group: GroupKeys; adjacentids: string[]; }[] = [
    { id: "AFR", name: 'Africa', group: 'INTER', adjacentids: [] },
    { id: "ASI", name: 'Asia', group: 'INTER', adjacentids: [] },
    { id: "OCE", name: 'Oceania', group: 'INTER', adjacentids: [] },
    { id: "EUR", name: 'Europe', group: 'INTER', adjacentids: [] },
    { id: "SAM", name: 'South America', group: 'INTER', adjacentids: [] },
    { id: "MB", name: "Manitoba", group: 'LAKES', adjacentids: [] },
    { id: "SK", name: "Saskatchewan", group: 'PLAINS', adjacentids: [] },
    { id: "AB", name: "Alberta", group: 'PLAINS', adjacentids: [] },
    { id: "BC", name: "British Columbia", group: 'WEST', adjacentids: [] },
    { id: "NU", name: "Nunavut", group: 'TERR', adjacentids: [] },
    { id: "NT", name: "Northwest Territories", group: 'TERR', adjacentids: [] },
    { id: "YT", name: "Yukon", group: 'TERR', adjacentids: [] },
    { id: "ON", name: "Ontario", group: 'LAKES', adjacentids: [] },
    { id: "QC", name: "Québec", group: 'NORTH', adjacentids: [] },
    { id: "NB", name: "New Brunswick", group: 'NORTH', adjacentids: [] },
    { id: "NS", name: "Nova Scotia", group: 'NORTH', adjacentids: [] },
    { id: "NL", name: "Newfoundland and Labrador", group: 'NORTH', adjacentids: [] },
    { id: "PE", name: "Prince Edward Island", group: 'NORTH', adjacentids: [] },
    { id: "MA", name: "Massachusetts", group: 'NORTH', adjacentids: [] },
    { id: "MN", name: "Minnesota", group: 'PLAINS', adjacentids: [] },
    { id: "MT", name: "Montana", group: 'PLAINS', adjacentids: [] },
    { id: "ND", name: "North Dakota", group: 'PLAINS', adjacentids: [] },
    { id: "ID", name: "Idaho", group: 'WEST', adjacentids: [] },
    { id: "WA", name: "Washington", group: 'WEST', adjacentids: [] },
    { id: "AZ", name: "Arizona", group: 'TEXAS', adjacentids: [] },
    { id: "CA", name: "California", group: 'WEST', adjacentids: [] },
    { id: "CO", name: "Colorado", group: 'PLAINS', adjacentids: [] },
    { id: "NV", name: "Nevada", group: 'WEST', adjacentids: [] },
    { id: "NM", name: "New Mexico", group: 'TEXAS', adjacentids: [] },
    { id: "OR", name: "Oregon", group: 'WEST', adjacentids: [] },
    { id: "UT", name: "Utah", group: 'PLAINS', adjacentids: [] },
    { id: "WY", name: "Wyoming", group: 'PLAINS', adjacentids: [] },
    { id: "AR", name: "Arkansas", group: 'TEXAS', adjacentids: [] },
    { id: "IA", name: "Iowa", group: 'LAKES', adjacentids: [] },
    { id: "KS", name: "Kansas", group: 'PLAINS', adjacentids: [] },
    { id: "MO", name: "Missouri", group: 'LAKES', adjacentids: [] },
    { id: "NE", name: "Nebraska", group: 'PLAINS', adjacentids: [] },
    { id: "OK", name: "Oklahoma", group: 'TEXAS', adjacentids: [] },
    { id: "SD", name: "South Dakota", group: 'PLAINS', adjacentids: [] },
    { id: "LA", name: "Louisiana", group: 'SOUTH', adjacentids: [] },
    { id: "TX", name: "Texas", group: 'TEXAS', adjacentids: [] },
    { id: "CT", name: "Connecticut", group: 'NORTH', adjacentids: [] },
    { id: "NH", name: "New Hampshire", group: 'NORTH', adjacentids: [] },
    { id: "RI", name: "Rhode Island", group: 'NORTH', adjacentids: [] },
    { id: "VT", name: "Vermont", group: 'NORTH', adjacentids: [] },
    { id: "AL", name: "Alabama", group: 'SOUTH', adjacentids: [] },
    { id: "FL", name: "Florida", group: 'SOUTH', adjacentids: [] },
    { id: "GA", name: "Georgia", group: 'SOUTH', adjacentids: [] },
    { id: "MS", name: "Mississippi", group: 'SOUTH', adjacentids: [] },
    { id: "SC", name: "South Carolina", group: 'SOUTH', adjacentids: [] },
    { id: "IL", name: "Illinois", group: 'LAKES', adjacentids: [] },
    { id: "IN", name: "Indiana", group: 'LAKES', adjacentids: [] },
    { id: "KY", name: "Kentucky", group: 'SOUTH', adjacentids: [] },
    { id: "NC", name: "North Carolina", group: 'SOUTH', adjacentids: [] },
    { id: "OH", name: "Ohio", group: 'LAKES', adjacentids: [] },
    { id: "TN", name: "Tennessee", group: 'SOUTH', adjacentids: [] },
    { id: "VA", name: "Virginia", group: 'URBIA', adjacentids: [] },
    { id: "WI", name: "Wisconsin", group: 'LAKES', adjacentids: [] },
    { id: "WV", name: "West Virginia", group: 'URBIA', adjacentids: [] },
    { id: "DE", name: "Delaware", group: 'URBIA', adjacentids: [] },
    { id: "DC", name: "District of Columbia", group: 'URBIA', adjacentids: [] },
    { id: "MD", name: "Maryland", group: 'URBIA', adjacentids: [] },
    { id: "NJ", name: "New Jersey", group: 'URBIA', adjacentids: [] },
    { id: "NY", name: "New York", group: 'URBIA', adjacentids: [] },
    { id: "PA", name: "Pennsylvania", group: 'URBIA', adjacentids: [] },
    { id: "ME", name: "Maine", group: 'NORTH', adjacentids: [] },
    { id: "MI", name: "Michigan", group: 'LAKES', adjacentids: [] },
    { id: "AK", name: "Alaska", group: 'WEST', adjacentids: [] },
    { id: "MX", name: "Mexico", group: 'TEXAS', adjacentids: [] },
    { id: "HI", name: "Hawaii", group: 'WEST', adjacentids: [] },
];
export const allLocationsStore = readable(Object.fromEntries(allLocations.map((loc) => [loc.id, loc])));
export const selectedLocationStore = writable<string | undefined>("AFR");
export type GroupKeys = 'NORTH' | 'SOUTH' | 'LAKES' | 'TEXAS' | 'WEST' | 'URBIA' | 'TERR' | 'INTER' | 'PLAINS';
export const groups: Record<GroupKeys, { color: string, label: string; }> = {
    'NORTH': {
        color: '#1982c4',
        label: 'Northeast',
    },
    'SOUTH': {
        color: '#ff595e',
        label: 'Southern US',
    },
    'LAKES': {
        color: '#8ac926',
        label: 'Great Lakes',
    },
    'TEXAS': {
        color: '#52a675',
        label: 'Greater Mexico',
    },
    'WEST': {
        color: '#4267ac',
        label: 'West Coast',
    },
    'URBIA': {
        color: '#c5ca30',
        label: 'Greater Metropolis',
    },
    'TERR': {
        color: '#ff924c',
        label: 'Territories',
    },
    'INTER': {
        color: '#6a4c93',
        label: 'International',
    },
    'PLAINS': {
        color: '#ffca3a',
        label: 'The Plains'
    }
};